# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Playwright tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-playwright
        python -m pip install playwright
        python -m pip install pytest-playwright-visual
    - name: Install playwright browser
      run: python -m playwright install firefox
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run pytest
      run: pytest --browser firefox
    - name: Archive screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/
    - name: Archive video recordings
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: videos
        path: videos/
